// Archivo de conexiones para el mapa de herramientas
// Contiene todas las conexiones entre nodos secundarios

// Función para obtener las conexiones del mapa
function getMapConnections() {
    return [
        // Conexiones de categorías a sus elementos
        // Motores Gráficos
        { data: { id: 'engines-unity', source: 'engines', target: 'unity' } },
        { data: { id: 'engines-unreal', source: 'engines', target: 'unreal' } },
        { data: { id: 'engines-godot', source: 'engines', target: 'godot' } },
        { data: { id: 'engines-touchdesigner', source: 'engines', target: 'touchdesigner' } },
        { data: { id: 'engines-processing', source: 'engines', target: 'processing' } },
        { data: { id: 'engines-openframeworks', source: 'engines', target: 'openframeworks' } },
        
        // Frameworks Web
        { data: { id: 'frameworks-p5', source: 'frameworks', target: 'p5' } },
        { data: { id: 'frameworks-three', source: 'frameworks', target: 'three' } },
        { data: { id: 'frameworks-babylon', source: 'frameworks', target: 'babylon' } },
        { data: { id: 'frameworks-tone', source: 'frameworks', target: 'tone' } },
        { data: { id: 'frameworks-nodejs', source: 'frameworks', target: 'nodejs' } },
        { data: { id: 'frameworks-websockets', source: 'frameworks', target: 'websockets' } },
        { data: { id: 'frameworks-ml5', source: 'frameworks', target: 'ml5' } },
        { data: { id: 'frameworks-hydra', source: 'frameworks', target: 'hydra' } },
        { data: { id: 'frameworks-xampp', source: 'frameworks', target: 'xampp' } },
        
        // Herramientas IA
        { data: { id: 'ia-comfy', source: 'ia', target: 'comfy' } },
        { data: { id: 'ia-n8n', source: 'ia', target: 'n8n' } },
        { data: { id: 'ia-pinokio', source: 'ia', target: 'pinokio' } },
        
        // IDEs
        { data: { id: 'ides-cursor', source: 'ides', target: 'cursor' } },
        { data: { id: 'ides-trae', source: 'ides', target: 'trae' } },
        { data: { id: 'ides-v0', source: 'ides', target: 'v0' } },
        { data: { id: 'ides-windsurf', source: 'ides', target: 'windsurf' } },
        { data: { id: 'ides-visual-studio', source: 'ides', target: 'visual-studio' } },
        
        // Shaders
        { data: { id: 'shaders-shadertoy', source: 'shaders', target: 'shadertoy' } },
        { data: { id: 'shaders-glsl', source: 'shaders', target: 'glsl' } },
        { data: { id: 'shaders-hlsl', source: 'shaders', target: 'hlsl' } },
        { data: { id: 'shaders-bookofshaders', source: 'shaders', target: 'bookofshaders' } },
        { data: { id: 'shaders-ejemplos-shaders', source: 'shaders', target: 'ejemplos-shaders' } },
        { data: { id: 'shaders-editor-shaders-live', source: 'shaders', target: 'editor-shaders-live' } },
        
        // Bases de Datos
        { data: { id: 'db-firebase', source: 'db', target: 'firebase' } },
        { data: { id: 'db-mongodb', source: 'db', target: 'mongodb' } },
        { data: { id: 'db-sql', source: 'db', target: 'sql' } },
        
        // Lenguajes de Programación
        { data: { id: 'languages-cpp', source: 'languages', target: 'cpp' } },
        { data: { id: 'languages-csharp', source: 'languages', target: 'csharp' } },
        { data: { id: 'languages-php', source: 'languages', target: 'php' } },
        { data: { id: 'languages-javascript', source: 'languages', target: 'javascript' } },
        { data: { id: 'languages-python', source: 'languages', target: 'python' } },
        { data: { id: 'languages-typescript', source: 'languages', target: 'typescript' } },
        { data: { id: 'languages-java', source: 'languages', target: 'java' } },
        { data: { id: 'languages-html', source: 'languages', target: 'html' } },
        { data: { id: 'languages-css', source: 'languages', target: 'css' } },
        { data: { id: 'languages-json', source: 'languages', target: 'json' } },
        { data: { id: 'languages-r', source: 'languages', target: 'r' } },
        { data: { id: 'languages-arduino', source: 'languages', target: 'arduino' } },
        
        // Frontend Frameworks
        { data: { id: 'frontend-react', source: 'frontend', target: 'react' } },
        { data: { id: 'frontend-vue', source: 'frontend', target: 'vue' } },
        { data: { id: 'frontend-svelte', source: 'frontend', target: 'svelte' } },
        { data: { id: 'frontend-angular', source: 'frontend', target: 'angular' } },
        { data: { id: 'frontend-nextjs', source: 'frontend', target: 'nextjs' } },
        
        // LLM Models
        { data: { id: 'llm-chatgpt', source: 'llm', target: 'chatgpt' } },
        { data: { id: 'llm-deepseek', source: 'llm', target: 'deepseek' } },
        { data: { id: 'llm-gemini', source: 'llm', target: 'gemini' } },
        { data: { id: 'llm-kimi', source: 'llm', target: 'kimi' } },
        { data: { id: 'llm-claude', source: 'llm', target: 'claude' } },
        
        // Sistemas Operativos
        { data: { id: 'os-windows', source: 'os', target: 'windows' } },
        { data: { id: 'os-linux', source: 'os', target: 'linux' } },
        { data: { id: 'os-mac', source: 'os', target: 'mac' } },
        { data: { id: 'os-android', source: 'os', target: 'android' } },
        { data: { id: 'os-ios', source: 'os', target: 'ios' } },
        
        // Soportes
        { data: { id: 'soportes-pantalla-touch', source: 'soportes', target: 'pantalla-touch' } },
        { data: { id: 'soportes-instalaciones-fisicas', source: 'soportes', target: 'instalaciones-fisicas' } },
        { data: { id: 'soportes-raspberry-pi', source: 'soportes', target: 'raspberry-pi' } },
        { data: { id: 'soportes-pantalla-led', source: 'soportes', target: 'pantalla-led' } },
        { data: { id: 'soportes-proyector', source: 'soportes', target: 'proyector' } },
        { data: { id: 'soportes-sitio-web', source: 'soportes', target: 'sitio-web' } },
        { data: { id: 'soportes-compilado-apk', source: 'soportes', target: 'compilado-apk' } },
        { data: { id: 'soportes-virtual-production', source: 'soportes', target: 'virtual-production' } },
        { data: { id: 'soportes-vr', source: 'soportes', target: 'vr' } },
        { data: { id: 'soportes-ar', source: 'soportes', target: 'ar' } },
        { data: { id: 'soportes-sonido', source: 'soportes', target: 'sonido' } },
        { data: { id: 'soportes-videojuegos', source: 'soportes', target: 'videojuegos' } },
        { data: { id: 'soportes-mapping', source: 'soportes', target: 'mapping' } },

        // Protocolos de Comunicación
        { data: { id: 'protocolos-websockets', source: 'protocolos', target: 'websockets' } },
        { data: { id: 'protocolos-spout', source: 'protocolos', target: 'spout' } },
        { data: { id: 'protocolos-syphon', source: 'protocolos', target: 'syphon' } },
        { data: { id: 'protocolos-ndi', source: 'protocolos', target: 'ndi' } },
        { data: { id: 'protocolos-webrtc', source: 'protocolos', target: 'webrtc' } },
        { data: { id: 'protocolos-osc', source: 'protocolos', target: 'osc' } },
        { data: { id: 'protocolos-api', source: 'protocolos', target: 'api' } },
        { data: { id: 'protocolos-midi', source: 'protocolos', target: 'midi' } },

        // Software Multimediales
        { data: { id: 'software-multimedia-resolume', source: 'software-multimedia', target: 'resolume' } },
        { data: { id: 'software-multimedia-blender', source: 'software-multimedia', target: 'blender' } },
        { data: { id: 'software-multimedia-paquete-adobe', source: 'software-multimedia', target: 'paquete-adobe' } },
        { data: { id: 'software-multimedia-obs', source: 'software-multimedia', target: 'obs' } },
        { data: { id: 'software-multimedia-cinema4d', source: 'software-multimedia', target: 'cinema4d' } },
        { data: { id: 'software-multimedia-ableton', source: 'software-multimedia', target: 'ableton' } },
        { data: { id: 'software-multimedia-puredata', source: 'software-multimedia', target: 'puredata' } },
        { data: { id: 'software-multimedia-guipper', source: 'software-multimedia', target: 'guipper' } },
        
        // Glosario
        { data: { id: 'glosario-livecoding', source: 'glosario', target: 'livecoding' } },
        { data: { id: 'glosario-vibecoding', source: 'glosario', target: 'vibecoding' } },
        { data: { id: 'glosario-programacion', source: 'glosario', target: 'programacion' } },
        { data: { id: 'glosario-prompting', source: 'glosario', target: 'prompting' } },
        { data: { id: 'glosario-consola', source: 'glosario', target: 'consola' } },
        { data: { id: 'glosario-script', source: 'glosario', target: 'script' } },
        { data: { id: 'glosario-compilado-interpretado', source: 'glosario', target: 'compilado-interpretado' } },
        { data: { id: 'glosario-formatos-exe', source: 'glosario', target: 'formatos-exe' } },
        { data: { id: 'glosario-drivers', source: 'glosario', target: 'drivers' } },
        { data: { id: 'glosario-mcp', source: 'glosario', target: 'mcp' } },
        
        // Algunas conexiones adicionales entre nodos relacionados (con clase 'secondary')
        { data: { id: 'three-glsl', source: 'three', target: 'glsl', type: 'secondary' } },
        { data: { id: 'javascript-typescript', source: 'javascript', target: 'typescript', type: 'secondary' } },
        { data: { id: 'unity-csharp', source: 'unity', target: 'csharp', type: 'secondary' } },
        { data: { id: 'unity-hlsl', source: 'unity', target: 'hlsl', type: 'secondary' } },
        { data: { id: 'unreal-cpp', source: 'unreal', target: 'cpp', type: 'secondary' } },
        { data: { id: 'unreal-hlsl', source: 'unreal', target: 'hlsl', type: 'secondary' } },
        { data: { id: 'godot-glsl', source: 'godot', target: 'glsl', type: 'secondary' } },
        { data: { id: 'blender-glsl', source: 'blender', target: 'glsl', type: 'secondary' } },
        { data: { id: 'processing-glsl', source: 'processing', target: 'glsl', type: 'secondary' } },
        { data: { id: 'touchdesigner-glsl', source: 'touchdesigner', target: 'glsl', type: 'secondary' } },
        { data: { id: 'p5-javascript', source: 'p5', target: 'javascript', type: 'secondary' } },
        { data: { id: 'p5-glsl', source: 'p5', target: 'glsl', type: 'secondary' } },
        { data: { id: 'babylon-glsl', source: 'babylon', target: 'glsl', type: 'secondary' } },
        { data: { id: 'touchdesigner-python', source: 'touchdesigner', target: 'python', type: 'secondary' } },
        { data: { id: 'touchdesigner-glsl', source: 'touchdesigner', target: 'glsl', type: 'secondary' } },
        { data: { id: 'processing-java', source: 'processing', target: 'java', type: 'secondary' } },
        { data: { id: 'nodejs-javascript', source: 'nodejs', target: 'javascript', type: 'secondary' } },
        { data: { id: 'nodejs-typescript', source: 'nodejs', target: 'typescript', type: 'secondary' } },
        { data: { id: 'openframeworks-cpp', source: 'openframeworks', target: 'cpp', type: 'secondary' } },
        { data: { id: 'comfy-python', source: 'comfy', target: 'python', type: 'secondary' } },
        { data: { id: 'n8n-python', source: 'n8n', target: 'python', type: 'secondary' } },
        { data: { id: 'pinokio-python', source: 'pinokio', target: 'python', type: 'secondary' } },
        { data: { id: 'ml5-javascript', source: 'ml5', target: 'javascript', type: 'secondary' } },
        { data: { id: 'hydra-javascript', source: 'hydra', target: 'javascript', type: 'secondary' } },
        { data: { id: 'arduino-cpp', source: 'arduino', target: 'cpp', type: 'secondary' } },
        { data: { id: 'pantalla-touch-android', source: 'pantalla-touch', target: 'android', type: 'secondary' } },
        { data: { id: 'instalaciones-fisicas-arduino', source: 'instalaciones-fisicas', target: 'arduino', type: 'secondary' } },
        { data: { id: 'raspberry-pi-linux', source: 'raspberry-pi', target: 'linux', type: 'secondary' } },
        { data: { id: 'sitio-web-javascript', source: 'sitio-web', target: 'javascript', type: 'secondary' } },
        { data: { id: 'sitio-web-css', source: 'sitio-web', target: 'css', type: 'secondary' } },
        { data: { id: 'sitio-web-html', source: 'sitio-web', target: 'html', type: 'secondary' } },
        { data: { id: 'sitio-web-nodejs', source: 'sitio-web', target: 'nodejs', type: 'secondary' } },
        { data: { id: 'sitio-web-typescript', source: 'sitio-web', target: 'typescript', type: 'secondary' } },
        { data: { id: 'compilado-apk-unity', source: 'compilado-apk', target: 'unity', type: 'secondary' } },
        { data: { id: 'compilado-apk-sitio-web', source: 'compilado-apk', target: 'sitio-web', type: 'secondary' } },
        { data: { id: 'compilado-apk-pantalla-touch', source: 'compilado-apk', target: 'pantalla-touch', type: 'secondary' } },
        { data: { id: 'xampp-javascript', source: 'xampp', target: 'javascript', type: 'secondary' } },
        { data: { id: 'xampp-php', source: 'xampp', target: 'php', type: 'secondary' } },
        { data: { id: 'xampp-sql', source: 'xampp', target: 'sql', type: 'secondary' } },
        { data: { id: 'sql-php', source: 'sql', target: 'php', type: 'secondary' } },
        { data: { id: 'spout-windows', source: 'spout', target: 'windows', type: 'secondary' } },
        { data: { id: 'syphon-mac', source: 'syphon', target: 'mac', type: 'secondary' } },
        { data: { id: 'frameworks-websockets', source: 'frameworks', target: 'websockets', type: 'secondary' } },
        { data: { id: 'blender-python', source: 'blender', target: 'python', type: 'secondary' } },
        { data: { id: 'paquete-adobe-javascript', source: 'paquete-adobe', target: 'javascript', type: 'secondary' } },
        { data: { id: 'obs-spout', source: 'obs', target: 'spout', type: 'secondary' } },
        { data: { id: 'obs-ndi', source: 'obs', target: 'ndi', type: 'secondary' } },
        { data: { id: 'vr-unity', source: 'vr', target: 'unity', type: 'secondary' } },
        { data: { id: 'vr-unreal', source: 'vr', target: 'unreal', type: 'secondary' } },
        { data: { id: 'ar-android', source: 'ar', target: 'android', type: 'secondary' } },
        { data: { id: 'virtual-production-unreal', source: 'virtual-production', target: 'unreal', type: 'secondary' } },
        { data: { id: 'ableton-sonido', source: 'ableton', target: 'sonido', type: 'secondary' } },
        { data: { id: 'ableton-osc', source: 'ableton', target: 'osc', type: 'secondary' } },
        { data: { id: 'ableton-midi', source: 'ableton', target: 'midi', type: 'secondary' } },
        { data: { id: 'puredata-sonido', source: 'puredata', target: 'sonido', type: 'secondary' } },
        { data: { id: 'puredata-osc', source: 'puredata', target: 'osc', type: 'secondary' } },
        { data: { id: 'puredata-midi', source: 'puredata', target: 'midi', type: 'secondary' } },
        { data: { id: 'resolume-osc', source: 'resolume', target: 'osc', type: 'secondary' } },
        { data: { id: 'resolume-midi', source: 'resolume', target: 'midi', type: 'secondary' } },
        { data: { id: 'resolume-ndi', source: 'resolume', target: 'ndi', type: 'secondary' } },
        { data: { id: 'resolume-spout', source: 'resolume', target: 'spout', type: 'secondary' } },
        // Eliminada la conexión entre Python y Resolume: { data: { id: 'resolume-python', source: 'resolume', target: 'python', type: 'secondary' } },
        { data: { id: 'guipper-osc', source: 'guipper', target: 'osc', type: 'secondary' } },
        { data: { id: 'guipper-spout', source: 'guipper', target: 'spout', type: 'secondary' } },
        { data: { id: 'guipper-ndi', source: 'guipper', target: 'ndi', type: 'secondary' } },
        { data: { id: 'videojuegos-unity', source: 'videojuegos', target: 'unity', type: 'secondary' } },
        { data: { id: 'videojuegos-godot', source: 'videojuegos', target: 'godot', type: 'secondary' } },
        { data: { id: 'videojuegos-unreal', source: 'videojuegos', target: 'unreal', type: 'secondary' } },
        { data: { id: 'videojuegos-javascript', source: 'videojuegos', target: 'javascript', type: 'secondary' } },
        { data: { id: 'videojuegos-three', source: 'videojuegos', target: 'three', type: 'secondary' } },
        { data: { id: 'vibecoding-ides', source: 'vibecoding', target: 'ides', type: 'secondary' } },
        { data: { id: 'livecoding-hydra', source: 'livecoding', target: 'hydra', type: 'secondary' } },
        { data: { id: 'livecoding-javascript', source: 'livecoding', target: 'javascript', type: 'secondary' } },
        { data: { id: 'livecoding-p5', source: 'livecoding', target: 'p5', type: 'secondary' } },
        { data: { id: 'livecoding-glsl', source: 'livecoding', target: 'glsl', type: 'secondary' } },
        { data: { id: 'editor-shaders-live-javascript', source: 'editor-shaders-live', target: 'javascript', type: 'secondary' } },
        { data: { id: 'editor-shaders-live-html', source: 'editor-shaders-live', target: 'html', type: 'secondary' } },
        { data: { id: 'editor-shaders-live-css', source: 'editor-shaders-live', target: 'css', type: 'secondary' } },
        { data: { id: 'editor-shaders-live-websockets', source: 'editor-shaders-live', target: 'websockets', type: 'secondary' } },
        { data: { id: 'editor-shaders-live-nodejs', source: 'editor-shaders-live', target: 'nodejs', type: 'secondary' } },
        
        // Conexiones con sistemas operativos
        { data: { id: 'unity-windows', source: 'unity', target: 'windows', type: 'secondary' } },
        { data: { id: 'unity-mac', source: 'unity', target: 'mac', type: 'secondary' } },
        { data: { id: 'unity-linux', source: 'unity', target: 'linux', type: 'secondary' } },
        { data: { id: 'unity-android', source: 'unity', target: 'android', type: 'secondary' } },
        { data: { id: 'unity-ios', source: 'unity', target: 'ios', type: 'secondary' } }
    ];
}
